### ISSUE TITLE
Should make a HTML import for loading external script

### ISSUE THREAD

**Issue by motss** [CaptainCodeman/sign-here#1]
Don't think it's a best practice to load external script right inside the element.
A better way is to create another `.html` file to HTML import the script.

https://github.com/CaptainCodeman/sign-here/blob/master/sign-here.html#L10

**Comment by CaptainCodeman** [comment]
I would agree if it was a more commonly used and loaded general purpose script (e.g. moment.js, d3.js etc...) that would be referenced from other elements as well and need the de-duping that the additional html import would provide but in this case it's unlikely to be loaded again for any other reason than for handling signature input so I think it's simpler (and one less http request) to just do it inline in the component.

Do you have a use-case where you're loading both the polymer element and the .js file directly / separately within the same app?

**Comment by motss** [comment]
I don't think it would save you any http request. IIRC it will dedupe duplicated dependencies and it won't load them more than once.

**Comment by CaptainCodeman** [comment]
I meant if you are using unbundled files, your app needs to load (1) sign-here element -> (2) script import element -> (3) script vs just (1) sign-here element -> (2) script

The script import element avoids the issue of multiple elements loading different versions of a script due to their own (possibly different) URL references. So yes, the html import does the de-duping but at a cost of that extra request (when unbundled). That makes sense if many things will possibly reference the script but less so if it's only likely to be used by one element only.

That's my reasoning for the choice.

**Comment by ktiedt** [comment]
Just to chime in on here, creating the extra HTML import file only dedupes things if other people are using the exact same file to import the same library, if its constrained to your own project (like it would be here) then you really gained nothing other than looking a bit prettier ;)

ie:
`<link rel="import" href="some-cool-lib.html">` (this projects local HTML import for 'some-cool-lib')
and
`<link rel="import" href="other-dep/some-cool-lib.html">` (other deps local HTML import for `some-cool-lib`)
Are seen as different requests since their resolved paths are not identical and would not really any benefit.

**Comment by CaptainCodeman** [comment]
You explained it better than I did 👍 

It would be nice if there were some common pattern of html imports being added for js-libs (which I think I recall seeing mentioned) or even a central bower-type repo of pointers to provide the de-duping (maybe part of poly-git?). I guess there are still some things to be worked out around versioning and of course a lot of it is chicken-and-egg when it comes to getting author support.

Right now I'm happy when I save duplicate requests within my own app!
